languageCode = "en-us"
title = "Azael Documentation"
theme = "docsy"
contentDir = "content"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
baseURL = "/"
# Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

disablePathToLower = true
enableGitInfo = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
disableHomeIcon = true
editURL = "https://github.com/Azael-Dev/azael-fivem-docs/edit/master/content"
github_repo = "https://github.com/Azael-Dev/azael-fivem-docs"
#github_project_repo = "https://github.com/Azael-Dev/azael-fivem-docs"
offlineSearch = true

[blackfriday]
hrefTargetBlank = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
name = "หน้าหลัก"
url = "https://fivem.azael.dev"
weight = 10

[[menu.main]]
name = "สินค้าของเรา"
url = "https://fivem.azael.dev/digishop"
weight = 20

[[menu.main]]
name = "เงื่อนไขการให้บริการ"
url = "https://fivem.azael.dev/page/terms-and-conditions/"
weight = 40

[params.ui]
sidebar_menu_compact = true
